spring:
  application:
    name: es
  datasource:
    url: jdbc:h2:mem:JPATest
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database: H2
    show-sql: true
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG