version: '3.7'
services:
  fastcampus-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: es-singlenode
    environment:
      - node.name=single
      - cluster.name=standalone
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
networks:
  elastic:
    driver: bridge